@include('frontend.layouts.links')
@include('frontend.blocks.small_header')
@include('frontend.blocks.navbar')
@yield('content')
@include('frontend.blocks.footer')
@include('frontend.layouts.scripts')
